export const mockCampaigns = [
  {
    id: 1,
    title: 'Tech Education for Underprivileged Youth',
    description:
      'Providing laptops and coding classes to underprivileged youth to empower them with tech skills for a brighter future.',
    category: 'education',
    startDate: '2025-03-01',
    endDate: '2025-06-30',
    goal: 50000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?coding,education',
  },
  {
    id: 2,
    title: 'Clean Water Initiative in Rural Africa',
    description:
      'Building wells and providing water purification systems to bring clean and safe drinking water to rural communities in Africa.',
    category: 'charity',
    startDate: '2025-02-15',
    endDate: '2025-05-15',
    goal: 75000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?cleanwater,africa',
  },
  {
    id: 3,
    title: 'Medical Research for Cancer Cure',
    description:
      'Funding cutting-edge medical research to discover new treatments and ultimately find a cure for cancer.',
    category: 'health',
    startDate: '2025-04-01',
    endDate: '2025-12-31',
    goal: 100000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?cancerresearch,medical',
  },
  {
    id: 4,
    title: 'Support Local Artists and Musicians',
    description:
      'Providing grants and platforms for local artists and musicians to showcase their talent and contribute to the cultural enrichment of our community.',
    category: 'other',
    startDate: '2025-03-15',
    endDate: '2025-09-15',
    goal: 30000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?localartists,music',
  },
  {
    id: 5,
    title: 'Environmental Conservation in the Amazon Rainforest',
    description:
      'Protecting the Amazon rainforest through reforestation projects and supporting sustainable practices among local communities.',
    category: 'technology',
    startDate: '2025-05-01',
    endDate: '2025-11-30',
    goal: 80000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?amazonrainforest,conservation',
  },
  {
    id: 6,
    title: 'Youth Sports Equipment Drive',
    description:
      'Collecting and distributing sports equipment to enable more children to participate in sports and develop healthy habits.',
    category: 'charity',
    startDate: '2025-01-10',
    endDate: '2025-04-10',
    goal: 20000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?youthsports,equipment',
  },
  {
    id: 7,
    title: 'Elderly Care and Companionship Program',
    description:
      'Providing companionship and assistance to elderly individuals to combat loneliness and improve their quality of life.',
    category: 'other',
    startDate: '2025-02-20',
    endDate: '2025-08-20',
    goal: 40000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?elderlycare,companionship',
  },
  {
    id: 8,
    title: 'Scholarships for STEM Students',
    description:
      'Offering scholarships to students pursuing degrees in science, technology, engineering, and mathematics to foster innovation and progress.',
    category: 'education',
    startDate: '2025-04-15',
    endDate: '2025-10-15',
    goal: 60000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?stemstudents,scholarships',
  },
  {
    id: 9,
    title: 'Mental Health Awareness Campaign',
    description:
      'Raising awareness about mental health issues and providing resources for individuals seeking support and treatment.',
    category: 'health',
    startDate: '2025-03-01',
    endDate: '2025-09-30',
    goal: 55000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?mentalhealth,awareness',
  },
  {
    id: 10,
    title: 'Community Garden Project',
    description:
      'Creating community gardens to provide fresh produce and promote sustainable living among urban residents.',
    category: 'other',
    startDate: '2025-05-10',
    endDate: '2025-11-10',
    goal: 25000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?communitygarden,urban',
  },
  {
    id: 11,
    title: 'Disaster Relief Fund for Earthquake Victims',
    description:
      'Providing immediate assistance and long-term support to individuals and communities affected by a devastating earthquake.',
    category: 'charity',
    startDate: '2025-01-01',
    endDate: '2025-07-01',
    goal: 120000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?earthquake,disasterrelief',
  },
  {
    id: 12,
    title: 'Coding Bootcamps for Women',
    description:
      'Offering intensive coding bootcamps specifically designed for women to increase their representation in the tech industry.',
    category: 'technology',
    startDate: '2025-02-01',
    endDate: '2025-08-01',
    goal: 90000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?womenincoding,bootcamps',
  },
  {
    id: 13,
    title: 'Free Eye Exams and Glasses for Children',
    description:
      'Providing free eye exams and prescription glasses to children from low-income families to improve their vision and academic performance.',
    category: 'health',
    startDate: '2025-03-15',
    endDate: '2025-09-15',
    goal: 45000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?eyeexams,children',
  },
  {
    id: 14,
    title: 'Preserving Historical Landmarks',
    description:
      'Restoring and preserving historical landmarks to protect our cultural heritage for future generations.',
    category: 'other',
    startDate: '2025-04-01',
    endDate: '2025-10-01',
    goal: 70000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?historicallandmarks,preservation',
  },
  {
    id: 15,
    title: 'Marine Life Conservation Project',
    description:
      'Protecting marine ecosystems and endangered species through research, conservation efforts, and community education.',
    category: 'technology',
    startDate: '2025-05-15',
    endDate: '2025-11-15',
    goal: 95000,
    imageVideoURL: 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60',
  },
  {
    id: 16,
    title: 'Supporting Small Farmers with Sustainable Agriculture',
    description:
      'Providing resources and training to small farmers to adopt sustainable agricultural practices and improve their livelihoods.',
    category: 'technology',
    startDate: '2025-06-01',
    endDate: '2025-12-01',
    goal: 60000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?sustainablefarming',
  },
  {
    id: 17,
    title: 'Providing Nutritious Meals to School Children',
    description:
      'Ensuring that school children have access to nutritious meals to support their health, growth, and academic performance.',
    category: 'health',
    startDate: '2025-07-01',
    endDate: '2026-01-01',
    goal: 55000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?schoolmeals',
  },
  {
    id: 18,
    title: 'Building Libraries in Rural Communities',
    description:
      'Constructing and stocking libraries in rural communities to promote literacy and provide access to knowledge and information.',
    category: 'education',
    startDate: '2025-08-01',
    endDate: '2026-02-01',
    goal: 70000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?rurallibraries',
  },
  {
    id: 19,
    title: 'Supporting Animal Shelters and Rescue Organizations',
    description:
      'Providing funding and resources to animal shelters and rescue organizations to care for abandoned and neglected animals.',
    category: 'charity',
    startDate: '2025-09-01',
    endDate: '2026-03-01',
    goal: 40000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?animalshelters',
  },
  {
    id: 20,
    title: 'Promoting Renewable Energy in Urban Areas',
    description:
      'Encouraging the adoption of renewable energy sources in urban areas to reduce carbon emissions and promote sustainable living.',
    category: 'other',
    startDate: '2025-10-01',
    endDate: '2026-04-01',
    goal: 80000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?renewableenergy,urban',
  },
  {
    id: 21,
    title: 'Providing Vocational Training for Unemployed Youth',
    description:
      'Offering vocational training programs to unemployed youth to equip them with skills for employment and entrepreneurship.',
    category: 'technology',
    startDate: '2025-11-01',
    endDate: '2026-05-01',
    goal: 65000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?vocationaltraining',
  },
  {
    id: 22,
    title: 'Supporting Research for Alzheimer\'s Disease',
    description:
      'Funding research to better understand, treat, and prevent Alzheimer\'s disease and improve the lives of those affected.',
    category: 'health',
    startDate: '2025-12-01',
    endDate: '2026-06-01',
    goal: 90000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?alzheimersresearch',
  },
  {
    id: 23,
    title: 'Creating Accessible Playgrounds for Children with Disabilities',
    description:
      'Building playgrounds that are accessible to children with disabilities to promote inclusion and provide opportunities for play and recreation.',
    category: 'charity',
    startDate: '2026-01-01',
    endDate: '2026-07-01',
    goal: 50000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?accessibleplaygrounds',
  },
  {
    id: 24,
    title: 'Promoting Sustainable Tourism in Developing Countries',
    description:
      'Supporting sustainable tourism initiatives in developing countries to promote economic growth while protecting the environment and local cultures.',
    category: 'other',
    startDate: '2026-02-01',
    endDate: '2026-08-01',
    goal: 75000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?sustainabletourism',
  },
  {
    id: 25,
    title: 'Providing Digital Literacy Training for Seniors',
    description:
      'Offering digital literacy training programs for seniors to help them stay connected, access information, and participate in the digital world.',
    category: 'technology',
    startDate: '2026-03-01',
    endDate: '2026-09-01',
    goal: 40000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?digitalliteracy',
  },
  {
    id: 26,
    title: 'Supporting Research for Childhood Cancer',
    description:
      'Funding research to develop new and more effective treatments for childhood cancer and improve the survival rates of young patients.',
    category: 'health',
    startDate: '2026-04-01',
    endDate: '2026-10-01',
    goal: 100000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?childhoodcancerresearch',
  },
  {
    id: 27,
    title: 'Building Schools in Impoverished Communities',
    description:
      'Constructing and equipping schools in impoverished communities to provide children with access to quality education.',
    category: 'education',
    startDate: '2026-05-01',
    endDate: '2026-11-01',
    goal: 80000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?schoolbuilding',
  },
  {
    id: 28,
    title: 'Protecting Endangered Species from Extinction',
    description:
      'Implementing conservation programs to protect endangered species and their habitats from extinction.',
    category: 'technology',
    startDate: '2026-06-01',
    endDate: '2026-12-01',
    goal: 90000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?endangeredspecies',
  },
  {
    id: 29,
    title: 'Providing Clean Energy Solutions for Rural Hospitals',
    description:
      'Offering clean energy solutions such as solar power to rural hospitals to ensure reliable electricity and reduce their carbon footprint.',
    category: 'health',
    startDate: '2026-07-01',
    endDate: '2027-01-01',
    goal: 60000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?cleanenergy,hospitals',
  },
  {
    id: 30,
    title: 'Supporting Local Farmers Markets',
    description:
      'Promoting local farmers markets to provide consumers with fresh, healthy produce and support local agriculture.',
    category: 'other',
    startDate: '2026-08-01',
    endDate: '2027-02-01',
    goal: 35000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?farmersmarket',
  },
  {
    id: 31,
    title: 'Providing Access to Technology for People with Disabilities',
    description:
      'Offering assistive technology and training to people with disabilities to help them access education, employment, and social opportunities.',
    category: 'technology',
    startDate: '2026-09-01',
    endDate: '2027-03-01',
    goal: 70000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?assistivetechnology',
  },
  {
    id: 32,
    title: 'Supporting Research for Heart Disease Prevention',
    description:
      'Funding research to identify risk factors for heart disease and develop effective prevention strategies.',
    category: 'health',
    startDate: '2026-10-01',
    endDate: '2027-04-01',
    goal: 85000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?heartdiseaseresearch',
  },
  {
    id: 33,
    title: 'Creating After-School Programs for At-Risk Youth',
    description:
      'Establishing after-school programs to provide at-risk youth with academic support, mentoring, and recreational activities.',
    category: 'education',
    startDate: '2026-11-01',
    endDate: '2027-05-01',
    goal: 55000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?afterschoolprograms',
  },
  {
    id: 34,
    title: 'Protecting Coral Reefs from Pollution and Climate Change',
    description:
      'Implementing conservation measures to protect coral reefs from the harmful effects of pollution and climate change.',
    category: 'technology',
    startDate: '2026-12-01',
    endDate: '2027-06-01',
    goal: 95000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?coralreefconservation',
  },
  {
    id: 35,
    title: 'Providing Mental Health Services for Veterans',
    description:
      'Offering mental health services and support to veterans to address issues such as PTSD, depression, and anxiety.',
    category: 'health',
    startDate: '2027-01-01',
    endDate: '2027-07-01',
    goal: 70000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?veteransmentalhealth',
  },
  {
    id: 36,
    title: 'Supporting Urban Farming Initiatives',
    description:
      'Promoting urban farming initiatives to provide fresh produce, create green spaces, and enhance community engagement in cities.',
    category: 'other',
    startDate: '2027-02-01',
    endDate: '2027-08-01',
    goal: 40000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?urbanfarming',
  },
  {
    id: 37,
    title: 'Promoting Cybersecurity Awareness and Education',
    description:
      'Raising awareness about cybersecurity threats and providing education to help individuals and organizations protect themselves online.',
    category: 'technology',
    startDate: '2027-03-01',
    endDate: '2027-09-01',
    goal: 65000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?cybersecurityawareness',
  },
  {
    id: 38,
    title: 'Supporting Research for Diabetes Prevention and Treatment',
    description:
      'Funding research to develop new strategies for preventing and treating diabetes and improving the lives of those living with the disease.',
    category: 'health',
    startDate: '2027-04-01',
    endDate: '2027-10-01',
    goal: 80000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?diabetesresearch',
  },
  {
    id: 39,
    title: 'Providing Educational Resources for Refugee Children',
    description:
      'Offering educational resources and support to refugee children to help them overcome barriers to education and succeed in school.',
    category: 'education',
    startDate: '2027-05-01',
    endDate: '2027-11-01',
    goal: 50000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?refugeechildreneducation',
  },
  {
    id: 40,
    title: 'Protecting Rainforests from Deforestation',
    description:
      'Implementing conservation programs to protect rainforests from deforestation and promote sustainable forest management.',
    category: 'technology',
    startDate: '2027-06-01',
    endDate: '2027-12-01',
    goal: 90000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?rainforestconservation',
  },
   {
    id: 41,
    title: 'Providing Clean Water in Indigenous Communities',
    description:
      'Providing clean water in Indigenous Communities to help them achieve financial stability and create a better future for their children.',
    category: 'charity',
    startDate: '2025-06-01',
    endDate: '2025-12-31',
    goal: 65000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?Indigenous,support',
  },
  {
    id: 42,
    title: 'Renewable Energy Solutions for Farms',
    description:
      'Helping farms adopt renewable energy solutions to reduce their carbon footprint and save on energy costs.',
    category: 'technology',
    startDate: '2025-07-15',
    endDate: '2026-01-15',
    goal: 85000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?renewableenergy,farms',
  },
  {
    id: 43,
    title: 'Free Mental Health Care for Low-Income Families',
    description:
      'Offering free mental health check-ups, cleanings, and treatments to low-income families who cannot afford regular mental health care.',
    category: 'health',
    startDate: '2025-08-01',
    endDate: '2026-02-28',
    goal: 50000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?freementalcare,lowincome',
  },
  {
    id: 44,
    title: 'Promoting Music and instruments in Schools',
    description:
      'Supporting music and instruments programs in schools to foster creativity and self-expression among students.',
    category: 'education',
    startDate: '2025-09-10',
    endDate: '2026-03-10',
    goal: 35000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?music,schools',
  },
  {
    id: 45,
    title: 'Protecting Wildlife in the Ocean',
    description:
      'Protecting endangered wildlife species and their habitats in the ocean through conservation efforts and anti-poaching patrols.',
    category: 'technology',
    startDate: '2025-10-01',
    endDate: '2026-04-30',
    goal: 95000,
    imageVideoURL: 'https://source.unsplash.com/400x225/?wildlifeprotection,ocean',
  },
  {
    id: 46,
    title: 'Campaign 46',
    description: 'Description 46',
    category: 'technology',
    startDate: '2024-06-01',
    endDate: '2024-06-30',
    goal: 6000,
    imageVideoURL: 'https://via.placeholder.com/400x225',
  },
  {
    id: 47,
    title: 'Campaign 47',
    description: 'Description 47',
    category: 'health',
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    goal: 7000,
    imageVideoURL: 'https://via.placeholder.com/400x225',
  },
  {
    id: 48,
    title: 'Campaign 48',
    description: 'Description 48',
    category: 'education',
    startDate: '2024-08-01',
    endDate: '2024-08-31',
    goal: 8000,
    imageVideoURL: 'https://via.placeholder.com/400x225',
  },
  {
    id: 49,
    title: 'Campaign 49',
    description: 'Description 49',
    category: 'charity',
    startDate: '2024-09-01',
    endDate: '2024-09-30',
    goal: 9000,
    imageVideoURL: 'https://via.placeholder.com/400x225',
  },
  {
    id: 50,
    title: 'Campaign 50',
    description: 'Description 50',
    category: 'other',
    startDate: '2024-10-01',
    endDate: '2024-10-31',
    goal: 10000,
    imageVideoURL: 'https://via.placeholder.com/400x225',
  },
];